version: '3'
services:
  websocket:
    image: node
    working_dir: /server
    volumes:
      - ./server:/server
    ports:
      - "3001:3001"
    command: bash -c "npm install && npm run start"
    networks:
      - common_net
  nextjs-app:
    image: node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:3000"
    env_file:
      - .env
    command: bash -c "npx prisma generate && npx prisma db push &&  npm run build && npm run start"
    networks:
      - common_net
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: kgbtr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - common_net
  
networks:
  common_net: {}